### ISSUE TITLE
Remove constant properties edges from the kgtk exploded file

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/t2wml-annotation#1]
All the following edges should be removed from the KGTK Exploded edge file, these are constant properties, we do not want them to import more than once

P2006020001-label-1 | P2006020001 | label | column index
-- | -- | -- | --
P2006020001-data_type-1 | P2006020001 | data_type | Quantity
P2006020001-description-1 | P2006020001 | description | Column number that corresponds to a variable
P2006020002-label-1 | P2006020002 | label | qualifier
P2006020002-description-1 | P2006020002 | description | Qualifiers used to describe a variable. E.g., FertilizerType, Source,   etc.
P2006020002-data_type-1 | P2006020002 | data_type | WikibaseProperty
P2006020003-label-1 | P2006020003 | label | variable measured
P2006020003-data_type-1 | P2006020003 | data_type | WikibaseItem
P2006020003-description-1 | P2006020003 | description | Variables that are measured in a Dataset
P2006020004-label-1 | P2006020004 | label | dataset
P2006020004-data_type-1 | P2006020004 | data_type | WikibaseItem
P2006020004-description-1 | P2006020004 | description | Id of the dataset this variable is included in
P2006020005-label-1 | P2006020005 | label | mapping file
P2006020005-data_type-1 | P2006020005 | data_type | String
P2006020006-label-1 | P2006020006 | label | keywords
P2006020006-description-1 | P2006020006 | description | Keywords describing the dataset. Multiple entries are delimited by commas
P2006020006-data-type-1 | P2006020006 | data_type | String
P2006020007-label-1 | P2006020007 | label | version
P2006020007-description-1 | P2006020007 | description | Version number of the Dataset. Semantic versioning in the form of X.Y.Z   is preferred (where X indicates a major version, Y a minor version and Z   indicates a patch or bug fixes)
P2006020007-data-type-1 | P2006020007 | data_type | String
P2006020008-label-1 | P2006020008 | label | date created
P2006020008-description-1 | P2006020008 | description | Creation date of the Dataset in ISO 8601 format (YYYY-MM-DD)
P2006020008-data-type-1 | P2006020008 | data_type | String
P2006020009-label-1 | P2006020009 | label | included in data catalog
P2006020009-description-1 | P2006020009 | description | Catalog where the Dataset is included
P2006020009-data-type-1 | P2006020009 | data_type | String
P2006180001-label-1 | P2006180001 | label | geospatial granularity
P2006180001-description-1 | P2006180001 | description | Administrative area (admin 1, admin 2 or admin 3) the variable or dataset   corresponds to
P2006180001-data-type-1 | P2006180001 | data_type | String
P2006190001-label-1 | P2006190001 | label | located in the first-level administrative country subdivision
P2006190001-description-1 | P2006190001 | description | The item is located in the first-level administrative country   subdivision. A first-level adminstrative country subdivision is located   within itself
P2006190001-data-type-1 | P2006190001 | data_type | WikibaseItem
P2006190002-label-1 | P2006190002 | label | located in the second-level administrative country subdivision
P2006190002-description-1 | P2006190002 | description | The item is located in the second-level administrative country   subdivision. A second-level adminstrative country subdivision is located   within itself
P2006190002-data-type-1 | P2006190002 | data_type | WikibaseItem
P2006190003-label-1 | P2006190003 | label | located in the third-level administrative country subdivision
P2006190003-description-1 | P2006190003 | description | The item is located in the third-level administrative country   subdivision. A third-level adminstrative country subdivision is located   within itself
P2006190003-data-type-1 | P2006190003 | data_type | WikibaseItem

**Comment by ckxz105** [comment]
So t2wml lite (scripts) still need this file internally, so we still need to pass this file, so I have add an option like:
```
    test = GenerateKgtk(annotated_spreadsheet=input_df, t2wml_script=t2wml_script,
                        dataset_qnode="test_node_id", add_datamart_constant_properties=False)
```
Default, `add_datamart_constant_properties` will be `False` so those part will not be appened as you required.
