### ISSUE TITLE
Add a parameter to accept Dataset Qnode 

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/t2wml-annotation#3]
In the function 
https://github.com/usc-isi-i2/t2wml-annotation/blob/master/annotation/generation/generate_kgtk.py#L97

We are not creating dataset metadata in this API so accept a Dataset Qnode and use it everywhere

**Comment by ckxz105** [comment]
It is unable to pass dataset id there as template output file is genearated during initialization, can we pass the id during initialization like this `GenerateKgtk(annotated_spreadsheet=input_df, t2wml_script=t2wml_script, dataset_id="test_id")` ?

**Comment by saggu** [comment]
@ckxz105 makes sense

**Comment by saggu** [comment]
@ckxz105 to be clear this would be dataset Qnode and not the dataset id. So parameter should be called `dataset_qnode` just to keep things consistent

**Comment by ckxz105** [comment]
I add a parameter like this:
```
    test = GenerateKgtk(annotated_spreadsheet=input_df, t2wml_script=t2wml_script,
                        dataset_qnode="test_node_id", add_datamart_constant_properties=False)
```
Where the `dataset_qnode` will be the things you required, if not given, default it will use the annotation file's dataset id.
