### ISSUE TITLE
Incorrect rows for the property `P2006020003`

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/t2wml-annotation#4]
The `node1` should the dataset QNODE, which will be passed as a parameter
```
Qaid-security-030-P2006020003-Qaid-security-030	Qaid-security-030	P2006020003	Qaid-security-030
```
Please see the attached file,

[t2wml-ann.csv.zip](https://github.com/usc-isi-i2/t2wml-annotation/files/4963282/t2wml-ann.csv.zip)

**Comment by ckxz105** [comment]
Sorry, this is a bug, I just fixed this, and not it support chang by passing dataset QNODE
